CAMERA_ID            = 0
TARGET_FPS           = 30
DEBOUNCE_FRAMES      = 4        # ~133ms @ 30fps
EXTEND_THRESHOLD     = 8000     # 手掌四边形面积阈值（像素²），需按摄像头分辨率标定
ZONE_TOP_BOUNDARY    = 0.35     # 归一化 y，小于此值为 TOP 区域
ZONE_BOTTOM_BOUNDARY = 0.65     # 归一化 y，大于此值为 BOTTOM 区域
SWIPE_MIN_VELOCITY   = 0.03     # 甩手触发最小速度（归一化坐标/帧）
SWIPE_FRAMES         = 5        # 计算甩手速度的滑动窗口帧数
DEBUG_LOG            = False
